In [3]:
[1 0 0]' * [1 0 0]

3×3 Array{Int64,2}:
 1  0  0
 0  0  0
 0  0  0

1×3 Array{Float64,2}:
 1.0  0.0  0.0

In [7]:
kron(eye(2),[1 0; 0 2])

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  2.0

In [14]:
eye(2) ⊗ [1 0]

2×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0

In [3]:
⊗(a,b) = kron(a,b)

⊗ (generic function with 1 method)

In [24]:
diagm(vec([1. 0. 0. 0.]))

16-element Array{Float64,1}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [7]:
eye(2) ⊗ [1;3;5]

6×2 Array{Float64,2}:
 1.0  0.0
 3.0  0.0
 5.0  0.0
 0.0  1.0
 0.0  3.0
 0.0  5.0

In [5]:
[1 2]' ⊗ eye(2)

4×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0
 2.0  0.0
 0.0  2.0

In [33]:
eye(2) ⊗ rand(4,4)

8×8 Array{Float64,2}:
 0.943186  0.265106  0.383345  0.285585  …  0.0       0.0       0.0     
 0.709054  0.289393  0.752217  0.936943     0.0       0.0       0.0     
 0.168019  0.790686  0.803838  0.458212     0.0       0.0       0.0     
 0.607952  0.798023  0.410459  0.735942     0.0       0.0       0.0     
 0.0       0.0       0.0       0.0          0.265106  0.383345  0.285585
 0.0       0.0       0.0       0.0       …  0.289393  0.752217  0.936943
 0.0       0.0       0.0       0.0          0.790686  0.803838  0.458212
 0.0       0.0       0.0       0.0          0.798023  0.410459  0.735942

In [38]:
a = [1 2 ; 3 4]
vec(eye(2))'*vec(a) == trace(a)

true

In [3]:
diagm([2;4;6])*[1 2 3; 4 5 6]

LoadError: DimensionMismatch("matrix A has dimensions (3,3), matrix B has dimensions (2,3)")

In [8]:
repmat([1;2],1,2) .* [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 6  8

In [11]:
([1;2;3] * ones(1, 5))'

5×3 Array{Float64,2}:
 1.0  2.0  3.0
 1.0  2.0  3.0
 1.0  2.0  3.0
 1.0  2.0  3.0
 1.0  2.0  3.0

In [12]:
S = [1 0 0 0; 0 0 0 1]

2×4 Array{Int64,2}:
 1  0  0  0
 0  0  0  1

In [15]:
S' * diagm([1; 2]) #* S

4×2 Array{Int64,2}:
 1  0
 0  0
 0  0
 0  2